version = 1

test_patterns = [
  "tests/*"
]

exclude_patterns = [
  "tests/*"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["pyproject.toml"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
